{% set version = '2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rflptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RFLPtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RFLPtools/RFLPtools_{{ version }}.tar.gz
  sha256: 0d40763f67426bdc216665bf58ef96e58138d60381ac39150ec3e3ee3d041c1e

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
  run:
    - r-base
    - r-rcolorbrewer

test:
  commands:
    - $R -e "library('RFLPtools')"           # [not win]
    - "\"%R%\" -e \"library('RFLPtools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RFLPtools
  license: LGPL-3.0-only
  summary: Provides functions to analyse DNA fragment samples (i.e. derived from RFLP-analysis)
    and standalone BLAST report files (i.e. DNA sequence analysis).
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
